/*
 * Title: Permission Baseline Seed
 * Version: v1 (Post-Mapping Stabilization)
 * Project: maatify/admin-control-panel
 *
 * Description:
 * - Generated from ACTUAL runtime usage
 * - Includes canonical + required standalone permissions
 * - Fully aligned with PermissionMapperV2
 *
 * Rules:
 * - DO NOT modify manually
 * - Regenerate via audit pipeline only
 */

INSERT INTO permissions (
    name,
    display_name,
    description
)
VALUES
    ('2fa.enable', 'Enable 2fa', 'Allows enable 2fa'),
    ('2fa.setup', 'Setup 2fa', 'Allows setup 2fa'),
    ('activity_logs.view', 'View Activity logs', 'Allows view activity logs'),
    ('admin.create', 'Create Admin', 'Allows create admin'),
    ('admin.email.add', 'Add Email Admin', 'Allows add email admin'),
    ('admin.email.fail', 'Fail Email Admin', 'Allows fail email admin'),
    ('admin.email.list', 'List Email Admin', 'Allows list email admin'),
    ('admin.email.replace', 'Replace Email Admin', 'Allows replace email admin'),
    ('admin.email.restart', 'Restart Email Admin', 'Allows restart email admin'),
    ('admin.email.verify', 'Verify Email Admin', 'Allows verify email admin'),
    ('admin.notifications.history', 'History Notifications Admin', 'Allows history notifications admin'),
    ('admin.notifications.read', 'Read Notifications Admin', 'Allows read notifications admin'),
    ('admin.permissions.direct.assign', 'Assign Direct Permissions Admin', 'Allows assign direct permissions admin'),
    ('admin.permissions.direct.assignable.query', 'Query Assignable Direct Permissions Admin', 'Allows query assignable direct permissions admin'),
    ('admin.permissions.direct.query', 'Query Direct Permissions Admin', 'Allows query direct permissions admin'),
    ('admin.permissions.direct.revoke', 'Revoke Direct Permissions Admin', 'Allows revoke direct permissions admin'),
    ('admin.permissions.effective', 'Effective Permissions Admin', 'Allows effective permissions admin'),
    ('admin.preferences.read', 'Read Preferences Admin', 'Allows read preferences admin'),
    ('admin.preferences.write', 'Write Preferences Admin', 'Allows write preferences admin'),
    ('admin.roles.query', 'Query Roles Admin', 'Allows query roles admin'),
    ('admins.list', 'List Admins', 'Allows list admins'),
    ('admins.permissions', 'Permissions Admins', 'Allows permissions admins'),
    ('admins.profile.edit', 'Edit Profile Admins', 'Allows edit profile admins'),
    ('admins.profile.view', 'View Profile Admins', 'Allows view profile admins'),
    ('admins.session.list', 'List Session Admins', 'Allows list session admins'),
    ('app_settings.create', 'Create App settings', 'Allows create app settings'),
    ('app_settings.list', 'List App settings', 'Allows list app settings'),
    ('app_settings.set_active', 'Set active App settings', 'Allows set active app settings'),
    ('app_settings.update', 'Update App settings', 'Allows update app settings'),
    ('auth.logout', 'Logout Auth', 'Allows logout auth'),
    ('auth.logout.web', 'Web Logout Auth', 'Allows web logout auth'),
    ('content_documents.acceptance.query', 'Query Acceptance Content documents', 'Allows query acceptance content documents'),
    ('content_documents.translations.details', 'Details Translations Content documents', 'Allows details translations content documents'),
    ('content_documents.translations.query', 'Query Translations Content documents', 'Allows query translations content documents'),
    ('content_documents.translations.upsert', 'Upsert Translations Content documents', 'Allows upsert translations content documents'),
    ('content_documents.types.create', 'Create Types Content documents', 'Allows create types content documents'),
    ('content_documents.types.dropdown', 'Dropdown Types Content documents', 'Allows dropdown types content documents'),
    ('content_documents.types.query', 'Query Types Content documents', 'Allows query types content documents'),
    ('content_documents.types.update', 'Update Types Content documents', 'Allows update types content documents'),
    ('content_documents.versions.activate', 'Activate Versions Content documents', 'Allows activate versions content documents'),
    ('content_documents.versions.archive', 'Archive Versions Content documents', 'Allows archive versions content documents'),
    ('content_documents.versions.create', 'Create Versions Content documents', 'Allows create versions content documents'),
    ('content_documents.versions.deactivate', 'Deactivate Versions Content documents', 'Allows deactivate versions content documents'),
    ('content_documents.versions.publish', 'Publish Versions Content documents', 'Allows publish versions content documents'),
    ('content_documents.versions.query', 'Query Versions Content documents', 'Allows query versions content documents'),
    ('i18n.domains.change_code', 'Change code Domains I18n', 'Allows change code domains i18n'),
    ('i18n.domains.create', 'Create Domains I18n', 'Allows create domains i18n'),
    ('i18n.domains.list', 'List Domains I18n', 'Allows list domains i18n'),
    ('i18n.domains.set_active', 'Set active Domains I18n', 'Allows set active domains i18n'),
    ('i18n.domains.update', 'Update Domains I18n', 'Allows update domains i18n'),
    ('i18n.domains.update_metadata', 'Update metadata Domains I18n', 'Allows update metadata domains i18n'),
    ('i18n.domains.update_sort', 'Update sort Domains I18n', 'Allows update sort domains i18n'),
    ('i18n.keys.list', 'List Keys I18n', 'Allows list keys i18n'),
    ('i18n.languages.dropdown', 'Dropdown Languages I18n', 'Allows dropdown languages i18n'),
    ('i18n.scopes.change_code', 'Change code Scopes I18n', 'Allows change code scopes i18n'),
    ('i18n.scopes.coverage.domain', 'Domain Coverage Scopes I18n', 'Allows domain coverage scopes i18n'),
    ('i18n.scopes.create', 'Create Scopes I18n', 'Allows create scopes i18n'),
    ('i18n.scopes.details', 'Details Scopes I18n', 'Allows details scopes i18n'),
    ('i18n.scopes.domains.assign', 'Assign Domains Scopes I18n', 'Allows assign domains scopes i18n'),
    ('i18n.scopes.domains.dropdown', 'Dropdown Domains Scopes I18n', 'Allows dropdown domains scopes i18n'),
    ('i18n.scopes.domains.keys', 'Keys Domains Scopes I18n', 'Allows keys domains scopes i18n'),
    ('i18n.scopes.domains.translations', 'Translations Domains Scopes I18n', 'Allows translations domains scopes i18n'),
    ('i18n.scopes.domains.unassign', 'Unassign Domains Scopes I18n', 'Allows unassign domains scopes i18n'),
    ('i18n.scopes.dropdown', 'Dropdown Scopes I18n', 'Allows dropdown scopes i18n'),
    ('i18n.scopes.keys', 'Keys Scopes I18n', 'Allows keys scopes i18n'),
    ('i18n.scopes.keys.create', 'Create Keys Scopes I18n', 'Allows create keys scopes i18n'),
    ('i18n.scopes.keys.update_metadata', 'Update metadata Keys Scopes I18n', 'Allows update metadata keys scopes i18n'),
    ('i18n.scopes.keys.update_name', 'Update name Keys Scopes I18n', 'Allows update name keys scopes i18n'),
    ('i18n.scopes.list', 'List Scopes I18n', 'Allows list scopes i18n'),
    ('i18n.scopes.set_active', 'Set active Scopes I18n', 'Allows set active scopes i18n'),
    ('i18n.scopes.update', 'Update Scopes I18n', 'Allows update scopes i18n'),
    ('i18n.scopes.update_metadata', 'Update metadata Scopes I18n', 'Allows update metadata scopes i18n'),
    ('i18n.scopes.update_sort', 'Update sort Scopes I18n', 'Allows update sort scopes i18n'),
    ('i18n.translations.list', 'List Translations I18n', 'Allows list translations i18n'),
    ('i18n.translations.upsert', 'Upsert Translations I18n', 'Allows upsert translations i18n'),
    ('languages.create', 'Create Languages', 'Allows create languages'),
    ('languages.list', 'List Languages', 'Allows list languages'),
    ('languages.set.active', 'Active Set Languages', 'Allows active set languages'),
    ('languages.set.fallback', 'Fallback Set Languages', 'Allows fallback set languages'),
    ('languages.translations.delete', 'Delete Translations Languages', 'Allows delete translations languages'),
    ('languages.translations.list', 'List Translations Languages', 'Allows list translations languages'),
    ('languages.translations.upsert', 'Upsert Translations Languages', 'Allows upsert translations languages'),
    ('languages.update.code', 'Code Update Languages', 'Allows code update languages'),
    ('languages.update.name', 'Name Update Languages', 'Allows name update languages'),
    ('languages.update.settings', 'Settings Update Languages', 'Allows settings update languages'),
    ('languages.update.sort', 'Sort Update Languages', 'Allows sort update languages'),
    ('notifications.list', 'List Notifications', 'Allows list notifications'),
    ('permission.details', 'Details Permission', 'Allows details permission'),
    ('permissions.admins.query', 'Query Admins Permissions', 'Allows query admins permissions'),
    ('permissions.metadata.update', 'Update Metadata Permissions', 'Allows update metadata permissions'),
    ('permissions.query', 'Query Permissions', 'Allows query permissions'),
    ('permissions.roles.query', 'Query Roles Permissions', 'Allows query roles permissions'),
    ('roles.admins.assign', 'Assign Admins Roles', 'Allows assign admins roles'),
    ('roles.admins.query', 'Query Admins Roles', 'Allows query admins roles'),
    ('roles.admins.unassign', 'Unassign Admins Roles', 'Allows unassign admins roles'),
    ('roles.admins.view', 'View Admins Roles', 'Allows view admins roles'),
    ('roles.create', 'Create Roles', 'Allows create roles'),
    ('roles.metadata.update', 'Update Metadata Roles', 'Allows update metadata roles'),
    ('roles.permissions.assign', 'Assign Permissions Roles', 'Allows assign permissions roles'),
    ('roles.permissions.query', 'Query Permissions Roles', 'Allows query permissions roles'),
    ('roles.permissions.unassign', 'Unassign Permissions Roles', 'Allows unassign permissions roles'),
    ('roles.permissions.view', 'View Permissions Roles', 'Allows view permissions roles'),
    ('roles.query', 'Query Roles', 'Allows query roles'),
    ('roles.rename', 'Rename Roles', 'Allows rename roles'),
    ('roles.toggle', 'Toggle Roles', 'Allows toggle roles'),
    ('roles.view', 'View Roles', 'Allows view roles'),
    ('sessions.list', 'List Sessions', 'Allows list sessions'),
    ('sessions.revoke', 'Revoke Sessions', 'Allows revoke sessions'),
    ('sessions.view_all', 'View all Sessions', 'Allows view all sessions'),
    ('telemetry.list', 'List Telemetry', 'Allows list telemetry');
