<?php

declare(strict_types=1);

namespace Maatify\Exceptions\Enum;

enum ErrorCodeEnum: string
{
    case MAATIFY_ERROR = 'MAATIFY_ERROR';

    case VALIDATION_FAILED = 'VALIDATION_FAILED';

    case INVALID_ARGUMENT = 'INVALID_ARGUMENT';
    case BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION';

    case RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    case CONFLICT = 'CONFLICT';

    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';

    case UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION';

    case DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED';

    case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
    case SESSION_EXPIRED = 'SESSION_EXPIRED';

    case AUTH_STATE_VIOLATION = 'AUTH_STATE_VIOLATION';
    case ENTITY_ALREADY_EXISTS = 'ENTITY_ALREADY_EXISTS';
    case ENTITY_IN_USE = 'ENTITY_IN_USE';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case INVALID_SESSION = 'INVALID_SESSION';
    case PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED';
    case PERMISSION_DENIED = 'PERMISSION_DENIED';
    case RECOVERY_LOCKED = 'RECOVERY_LOCKED';
    case SESSION_REVOKED = 'SESSION_REVOKED';
    case ALREADY_ENROLLED = 'ALREADY_ENROLLED';
    case ENROLLMENT_FAILED = 'ENROLLMENT_FAILED';
    case INVALID_OPERATION = 'INVALID_OPERATION';
}
